#line 1 "l2c_lex.cpp"

#line 3 "l2c_lex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer l2c_create_buffer
#define yy_delete_buffer l2c_delete_buffer
#define yy_scan_buffer l2c_scan_buffer
#define yy_scan_string l2c_scan_string
#define yy_scan_bytes l2c_scan_bytes
#define yy_init_buffer l2c_init_buffer
#define yy_flush_buffer l2c_flush_buffer
#define yy_load_buffer_state l2c_load_buffer_state
#define yy_switch_to_buffer l2c_switch_to_buffer
#define yypush_buffer_state l2cpush_buffer_state
#define yypop_buffer_state l2cpop_buffer_state
#define yyensure_buffer_stack l2censure_buffer_stack
#define yy_flex_debug l2c_flex_debug
#define yyin l2cin
#define yyleng l2cleng
#define yylex l2clex
#define yylineno l2clineno
#define yyout l2cout
#define yyrestart l2crestart
#define yytext l2ctext
#define yywrap l2cwrap
#define yyalloc l2calloc
#define yyrealloc l2crealloc
#define yyfree l2cfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define l2c_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer l2c_create_buffer
#endif

#ifdef yy_delete_buffer
#define l2c_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer l2c_delete_buffer
#endif

#ifdef yy_scan_buffer
#define l2c_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer l2c_scan_buffer
#endif

#ifdef yy_scan_string
#define l2c_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string l2c_scan_string
#endif

#ifdef yy_scan_bytes
#define l2c_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes l2c_scan_bytes
#endif

#ifdef yy_init_buffer
#define l2c_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer l2c_init_buffer
#endif

#ifdef yy_flush_buffer
#define l2c_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer l2c_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define l2c_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state l2c_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define l2c_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer l2c_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define l2cpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state l2cpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define l2cpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state l2cpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define l2censure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack l2censure_buffer_stack
#endif

#ifdef yylex
#define l2clex_ALREADY_DEFINED
#else
#define yylex l2clex
#endif

#ifdef yyrestart
#define l2crestart_ALREADY_DEFINED
#else
#define yyrestart l2crestart
#endif

#ifdef yylex_init
#define l2clex_init_ALREADY_DEFINED
#else
#define yylex_init l2clex_init
#endif

#ifdef yylex_init_extra
#define l2clex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra l2clex_init_extra
#endif

#ifdef yylex_destroy
#define l2clex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy l2clex_destroy
#endif

#ifdef yyget_debug
#define l2cget_debug_ALREADY_DEFINED
#else
#define yyget_debug l2cget_debug
#endif

#ifdef yyset_debug
#define l2cset_debug_ALREADY_DEFINED
#else
#define yyset_debug l2cset_debug
#endif

#ifdef yyget_extra
#define l2cget_extra_ALREADY_DEFINED
#else
#define yyget_extra l2cget_extra
#endif

#ifdef yyset_extra
#define l2cset_extra_ALREADY_DEFINED
#else
#define yyset_extra l2cset_extra
#endif

#ifdef yyget_in
#define l2cget_in_ALREADY_DEFINED
#else
#define yyget_in l2cget_in
#endif

#ifdef yyset_in
#define l2cset_in_ALREADY_DEFINED
#else
#define yyset_in l2cset_in
#endif

#ifdef yyget_out
#define l2cget_out_ALREADY_DEFINED
#else
#define yyget_out l2cget_out
#endif

#ifdef yyset_out
#define l2cset_out_ALREADY_DEFINED
#else
#define yyset_out l2cset_out
#endif

#ifdef yyget_leng
#define l2cget_leng_ALREADY_DEFINED
#else
#define yyget_leng l2cget_leng
#endif

#ifdef yyget_text
#define l2cget_text_ALREADY_DEFINED
#else
#define yyget_text l2cget_text
#endif

#ifdef yyget_lineno
#define l2cget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno l2cget_lineno
#endif

#ifdef yyset_lineno
#define l2cset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno l2cset_lineno
#endif

#ifdef yywrap
#define l2cwrap_ALREADY_DEFINED
#else
#define yywrap l2cwrap
#endif

#ifdef yyalloc
#define l2calloc_ALREADY_DEFINED
#else
#define yyalloc l2calloc
#endif

#ifdef yyrealloc
#define l2crealloc_ALREADY_DEFINED
#else
#define yyrealloc l2crealloc
#endif

#ifdef yyfree
#define l2cfree_ALREADY_DEFINED
#else
#define yyfree l2cfree
#endif

#ifdef yytext
#define l2ctext_ALREADY_DEFINED
#else
#define yytext l2ctext
#endif

#ifdef yyleng
#define l2cleng_ALREADY_DEFINED
#else
#define yyleng l2cleng
#endif

#ifdef yyin
#define l2cin_ALREADY_DEFINED
#else
#define yyin l2cin
#endif

#ifdef yyout
#define l2cout_ALREADY_DEFINED
#else
#define yyout l2cout
#endif

#ifdef yy_flex_debug
#define l2c_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug l2c_flex_debug
#endif

#ifdef yylineno
#define l2clineno_ALREADY_DEFINED
#else
#define yylineno l2clineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[400] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   79,   77,   74,   73,   71,   72,
       77,   77,   77,    3,    3,    2,    3,    3,    3,    3,
        3,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   37,
       38,   39,   41,   42,   40,   43,   44,   45,   46,   47,
       48,   49,   52,   53,   54,   55,   57,   56,   36,   35,
       66,   64,   77,   68,   77,   59,   58,   60,   61,   63,
       62,    0,    0,    0,    0,    0,    3,    3,    3,    3,

        3,    3,    3,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   41,   43,   50,   51,   52,   56,
       35,   65,   67,   62,   76,    0,   75,    0,    0,    3,
        3,    3,    3,    3,    3,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,    0,    0,
        0,    3,    3,    3,    3,   34,   22,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   34,   70,    0,    3,    3,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   23,   34,   34,   34,   34,   34,   34,   34,    0,
       34,   34,    0,    3,    3,   17,   34,   34,   34,   34,
       34,   19,   34,   34,   18,   34,   34,   34,   34,   34,
       34,   24,   34,   34,   34,    7,   34,   34,   34,    0,
       27,   26,    0,    3,    3,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,    9,   34,
       34,   34,   14,   34,   34,    0,    0,    0,    3,    3,
        3,   21,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   25,   34,   34,   34,    0,   15,   34,   34,    0,
       69,    3,   34,   34,   34,   34,   34,   34,    8,   34,
       34,   29,   28,   34,    0,   34,   34,    0,    3,   34,
       34,   34,   34,   20,   34,   34,   34,   34,    0,   34,
       16,    0,    3,   34,   34,   34,   34,   34,   34,    0,
       34,    0,   13,    0,    3,   34,   34,   34,   34,   34,
       34,    0,   34,    0,    0,    3,   31,   34,   34,   34,
       10,   34,    0,   34,    0,    0,    3,   34,   34,   30,
       12,    0,   34,    6,    5,    3,   34,   34,    0,   11,
        3,   33,   34,    0,    1,   32,    0,    4,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    8,
        9,    1,    1,   10,   11,   12,    1,   13,   13,   14,
       13,   13,   13,   13,   13,   13,   13,   15,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   21,   23,   24,
       21,   21,   25,   21,   21,   26,   21,   27,   21,   21,
       21,   28,   29,   21,   21,   30,   21,   21,   21,   21,
        1,   31,    1,    1,   21,    1,   32,   21,   33,   34,

       35,   36,   37,   38,   39,   21,   21,   40,   41,   42,
       43,   44,   21,   45,   46,   47,   48,   49,   50,   51,
       52,   21,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static const flex_int16_t yy_base[418] =
    {   0,
        0,   13,   26,   39,   53,  755,  105,  136,  167,  198,
      229,  260,  291,  322,  352,  382,  412,  442,  472,  487,
      502,  516,  531,  562,  760,  762,  762,  762,  762,  762,
        8,   22,    7,    0,    0,  762,    0,    0,   10,   36,
      121,  708,    0,  716,  715,  709,  720,  703,  710,  717,
      709,   89,   90,  315,  706,  704,  709,  710,  707,  762,
      762,  762,  116,  762,  762,    0,  762,  762,  762,  762,
      728,  725,    0,  762,  762,  762,  762,    0,  762,    0,
      762,  762,  738,  762,  735,  762,  762,  762,  762,  762,
        0,  336,  366,  144,  146,  702,    0,  394,  397,  150,

      174,  701,  694,    0,  699,  703,  163,  704,  690,  695,
      691,  318,  698,  686,  687,  687,  681,  676,  692,  680,
      681,  681,  677,  679,  180,    0,  762,  762,    0,    0,
        0,  762,  762,    0,  762,  426,  762,  182,  678,    0,
      427,    0,  205,  677,  686,  674,  205,  681,  680,  675,
      668,  673,  668,  664,  666,  669,  324,  664,  658,  662,
      669,  664,  654,  658,  215,  663,  656,  664,  694,  364,
      661,  692,  368,  659,  656,  651,  762,  659,  654,  639,
      651,  640,  650,  644,  645,  642,  633,  636,  643,  640,
      630,  633,  631,  630,  633,  633,  638,  623,  635,  665,

      620,  624,  762,  662,  661,  623,  648,  629,  614,  105,
      622,  235,  607,  643,  623,  612,  623,  611,  608,  610,
      607,    0,  615,  605,  600,  612,  598,  612,  602,  617,
      598,  591,  208,  210,  608,  762,  601,  616,  602,  597,
      588,  762,  602,  604,  762,  597,  588,  583,  580,  582,
      588,    0,  604,  571,  551,    0,  558,  356,  544,  578,
        0,    0,  212,  238,  584,  572,  543,  549,  547,  561,
      549,  514,  515,  513,  519,  513,  508,  512,  762,  519,
      549,  517,    0,  512,  488,  480,  522,  425,  521,  428,
      487,  762,  470,  464,  472,  465,  464,  453,  482,  457,

      452,    0,  443,  433,  435,  447,    0,  437,  431,  420,
      762,  457,  423,  447,  421,  423,  449,  422,  762,  413,
      417,    0,    0,  426,  422,  398,  384,  389,  410,  394,
      384,  400,  365,  762,  367,  366,  400,  354,  356,  384,
        0,  351,  393,  342,  333,  327,  334,  331,  309,  308,
      307,  298,  762,  309,  297,  295,  274,  278,  268,  303,
      275,  281,  272,  276,  272,  265,    0,  276,  243,  242,
      762,  273,  245,  244,  270,  269,  251,  231,  246,    0,
      762,  243,  242,  762,  762,  211,  208,  203,  206,  762,
      180,    0,  150,  128,    0,    0,  120,  762,  762,  593,

      596,  599,  602,  605,  608,  611,  614,   34,   29,    7,
        6,    5,    3,  617,  620,  623,  626
    } ;

static const flex_int16_t yy_def[418] =
    {   0,
      400,  400,  401,  401,  399,    5,  402,  402,  403,  403,
      404,  404,  405,  405,  400,  400,  400,  400,  400,  400,
      400,  400,  406,  406,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  407,  407,  399,  407,  407,  407,  407,
      407,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  399,
      399,  399,  399,  399,  399,  409,  399,  399,  399,  399,
      399,  399,  410,  399,  399,  399,  399,  411,  399,  412,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      413,  399,  399,  399,  399,  399,  407,  407,  407,  407,

      407,  407,  407,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  399,  409,  399,  399,  410,  411,
      412,  399,  399,  413,  399,  399,  399,  414,  399,  407,
      407,  407,  415,  407,  407,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  414,  414,
      399,  415,  415,  407,  407,  408,  399,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  399,  399,  407,  407,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  399,
      408,  408,  399,  407,  407,  399,  408,  408,  408,  408,
      408,  399,  408,  408,  399,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  399,
      408,  408,  416,  417,  407,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  399,  408,
      408,  408,  408,  408,  408,  399,  416,  416,  417,  417,
      407,  399,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  399,  408,  408,  408,  399,
      399,  407,  408,  408,  408,  408,  408,  408,  399,  408,
      408,  408,  408,  408,  399,  408,  408,  399,  407,  408,
      408,  408,  408,  399,  408,  408,  408,  408,  399,  408,
      408,  399,  407,  408,  408,  408,  408,  408,  408,  399,
      408,  399,  399,  399,  407,  408,  408,  408,  408,  408,
      408,  399,  408,  399,  399,  407,  408,  408,  408,  408,
      399,  408,  399,  408,  399,  399,  407,  408,  408,  408,
      399,  399,  408,  399,  399,  407,  408,  408,  399,  399,
      407,  408,  408,  399,  407,  408,  399,  399,    0,  399,

      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399
    } ;

static const flex_int16_t yy_nxt[815] =
    {   0,
      399,   27,   28,   27,   29,  134,   30,  131,  130,  129,
       95,   31,   32,   32,   27,   28,   27,   29,   33,   30,
       92,   92,   98,   98,   31,   32,   32,   35,   36,   35,
       37,  126,   38,   93,   94,   94,  104,   39,   40,   40,
       35,   36,   35,   37,   41,   38,   96,   99,  100,  100,
       39,   40,   40,   26,   27,   28,   27,   29,   26,   30,
       26,   26,   26,   26,   31,   32,   32,   26,   26,   26,
       26,   26,   42,   43,   43,   44,   43,   45,   43,   43,
       43,   46,   47,   26,   48,   49,   50,   51,   43,   52,
       43,   53,   43,   54,   55,   43,   56,   57,   43,   43,

       43,   58,   59,   43,   43,   26,   27,   28,   27,   29,
       26,   30,   60,   61,   62,   26,   31,   63,   63,   26,
       64,   26,   65,   26,  101,  114,  116,   93,  125,  125,
      239,  117,  240,  115,  398,   26,   26,   27,   28,   27,
       29,   33,   30,   60,   61,   62,   26,   31,   63,   63,
       26,   64,   26,   65,   26,   93,   94,   94,  138,  138,
      102,   99,  100,  100,  103,  397,   26,   26,   27,   28,
       27,   29,   26,   30,   67,   68,   69,   26,   31,   32,
       32,   70,   26,   71,   26,   72,  143,  143,  148,  149,
      150,   93,  125,  125,  170,  170,  396,   26,   26,   27,

       28,   27,   29,   33,   30,   67,   68,   69,   26,   31,
       32,   32,   70,   26,   71,   26,   72,  173,  173,  177,
      263,  263,  264,  264,  288,  288,  395,  178,   26,   26,
       27,   28,   27,   29,   26,   30,   74,   75,   76,   26,
       31,   32,   32,   26,   77,   26,   26,   26,  198,  242,
      290,  290,  394,  393,  392,  391,  390,  243,  199,   26,
       26,   27,   28,   27,   29,   33,   30,   74,   75,   76,
       26,   31,   32,   32,   26,   77,   26,   26,   26,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
       26,   26,   27,   28,   27,   29,   26,   30,   26,   26,

       26,   26,   31,   32,   32,   26,   79,   26,   26,   26,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,   26,   26,   27,   28,   27,   29,   33,   30,   26,
       26,   26,   26,   31,   32,   32,   26,   79,   26,   26,
       26,  367,  366,  365,  364,  363,  118,  362,   92,   92,
      155,  361,   26,   27,   28,   27,   81,  119,   82,  135,
      188,  135,  156,   31,   32,   32,  203,  360,  359,  358,
      203,  135,  189,  190,  357,  135,  170,  170,  136,  136,
      173,  173,   83,   27,   28,   27,   81,   33,   82,  137,
      283,  137,  356,   31,   32,   32,  355,  354,  353,  352,

      351,  137,  284,  350,  349,  137,   98,   98,  348,  141,
      141,  347,   83,   27,   28,   27,   29,  140,   84,  140,
      142,  346,  142,   31,   32,   32,  345,  311,  344,  140,
      311,  343,  142,  140,  342,  341,  142,  288,  288,  340,
      290,  290,   85,   27,   28,   27,   29,   33,   84,  137,
      142,  137,  142,   31,   32,   32,  339,  338,  337,  336,
      335,  137,  142,  334,  333,  137,  142,  332,  331,  330,
      329,  328,   85,   27,   28,   27,   29,  327,   30,  326,
      325,  324,  323,   31,   32,   32,  322,   86,   27,   28,
       27,   29,   33,   30,  321,  320,  319,  318,   31,   32,

       32,  317,   86,   27,   28,   27,   29,  316,   30,  315,
      314,  313,  312,   31,   63,   63,   87,   27,   28,   27,
       29,   33,   30,  311,  311,  310,  309,   31,   63,   63,
       87,   26,   27,   28,   27,   29,   26,   30,   88,   89,
       90,   26,   31,   32,   32,   26,   26,   26,   26,   26,
      308,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,   26,   26,   27,   28,   27,   29,   33,   30,   88,
       89,   90,   26,   31,   32,   32,   26,   26,   26,   26,
       26,  297,  296,  295,  294,  293,  292,  291,  286,  285,
      282,  281,   26,   26,   26,   26,   34,   34,   34,   66,

       66,   66,   73,   73,   73,   78,   78,   78,   80,   80,
       80,   91,   91,   91,   97,  280,   97,  169,  279,  169,
      172,  278,  172,  287,  277,  287,  289,  276,  289,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  241,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  203,  204,  203,  202,  201,  200,

      197,  196,  195,  194,  193,  192,  191,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  176,  175,  174,  171,
      168,  167,  166,  165,  164,  163,  162,  161,  160,  159,
      158,  157,  154,  153,  152,  151,  147,  146,  145,  144,
      139,  133,  132,  128,  127,  124,  123,  122,  121,  120,
      113,  112,  111,  110,  109,  108,  107,  106,  105,  399,
       33,   25,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399
    } ;

static const flex_int16_t yy_chk[815] =
    {   0,
        0,    1,    1,    1,    1,  413,    1,  412,  411,  410,
       33,    1,    1,    1,    2,    2,    2,    2,    2,    2,
       31,   31,   39,   39,    2,    2,    2,    3,    3,    3,
        3,  409,    3,   32,   32,   32,  408,    3,    3,    3,
        4,    4,    4,    4,    4,    4,   33,   40,   40,   40,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   41,   52,   53,   63,   63,   63,
      210,   53,  210,   52,  397,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,   94,   94,   94,   95,   95,
       41,  100,  100,  100,   41,  394,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,  101,  101,  107,  107,
      107,  125,  125,  125,  138,  138,  393,    9,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,  143,  143,  147,
      233,  233,  234,  234,  263,  263,  391,  147,   10,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,  165,  212,
      264,  264,  389,  388,  387,  386,  383,  212,  165,   11,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,  382,
      379,  378,  377,  376,  375,  374,  373,  372,  370,  369,
       12,   13,   13,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
      368,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,   13,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,  356,  355,  354,  352,  351,   54,  350,   92,   92,
      112,  349,   14,   15,   15,   15,   15,   54,   15,   92,
      157,   92,  112,   15,   15,   15,  170,  348,  347,  346,
      173,   92,  157,  157,  345,   92,  170,  170,   93,   93,
      173,  173,   15,   16,   16,   16,   16,   16,   16,   93,
      258,   93,  344,   16,   16,   16,  343,  342,  340,  339,

      338,   93,  258,  337,  336,   93,   98,   98,  335,   99,
       99,  333,   16,   17,   17,   17,   17,   98,   17,   98,
       99,  332,   99,   17,   17,   17,  331,  288,  330,   98,
      290,  329,   99,   98,  328,  327,   99,  288,  288,  326,
      290,  290,   17,   18,   18,   18,   18,   18,   18,  136,
      141,  136,  141,   18,   18,   18,  325,  324,  321,  320,
      318,  136,  141,  317,  316,  136,  141,  315,  314,  313,
      312,  310,   18,   19,   19,   19,   19,  309,   19,  308,
      306,  305,  304,   19,   19,   19,  303,   19,   20,   20,
       20,   20,   20,   20,  301,  300,  299,  298,   20,   20,

       20,  297,   20,   21,   21,   21,   21,  296,   21,  295,
      294,  293,  291,   21,   21,   21,   21,   22,   22,   22,
       22,   22,   22,  289,  287,  286,  285,   22,   22,   22,
       22,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
      284,  282,  281,  280,  278,  277,  276,  275,  274,  273,
      272,   23,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,  271,  270,  269,  268,  267,  266,  265,  260,  259,
      257,  255,   24,  400,  400,  400,  401,  401,  401,  402,

      402,  402,  403,  403,  403,  404,  404,  404,  405,  405,
      405,  406,  406,  406,  407,  254,  407,  414,  253,  414,
      415,  251,  415,  416,  250,  416,  417,  249,  417,  248,
      247,  246,  244,  243,  241,  240,  239,  238,  237,  235,
      232,  231,  230,  229,  228,  227,  226,  225,  224,  223,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  211,
      209,  208,  207,  206,  205,  204,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  176,  175,  174,  172,  171,  169,  168,  167,  166,

      164,  163,  162,  161,  160,  159,  158,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  146,  145,  144,  139,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  111,  110,  109,  108,  106,  105,  103,  102,
       96,   85,   83,   72,   71,   59,   58,   57,   56,   55,
       51,   50,   49,   48,   47,   46,   45,   44,   42,   25,
        6,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,

      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "l2c.l"
#line 2 "l2c.l"

#include <assert.h>
#include <string.h>


#define YY_NEVER_INTERACTIVE 1

#include <lparams.h>

#include "module.h"
#include "contextdata.h"
#include "l2c_yacc.h"
#include "maxpath.h"

extern ModuleTable moduleTable;

extern bool bModulesOnly; // Mik 04/2013 - check if parser is in ModulesOnly state

// Pascal New version of Flex
#ifdef __cplusplus
extern "C"
{
#endif /* __cplusplus */
extern int isatty( int );
#ifdef __cplusplus
}
#endif /* __cplusplus */



extern "C" int l2cwrap()
{ return 1; }

int nested;
int lineno = 1;
bool first_time = true;
int BeforeString;
char FileName[MaxPath+3];


bool verbose = false;
void DumpOut(const char*);
void SetCurLine(const char* bf)
{
	sscanf(bf, "%d %s", &lineno, FileName);
}


#line 1065 "l2c_lex.cpp"
/* Mik 04/2013 - add SKIP state to skip lines before "#pragma L2C start" */
/*               (below) add rules for skipping header before the L2C directive */

#line 1069 "l2c_lex.cpp"

#define INITIAL 0
#define SKIP 1
#define NRMLSRC 2
#define MODULE 3
#define PRODPROTO 4
#define PRODUCTION 5
#define CONIGN 6
#define STRING 7
#define CHARACTER 8
#define EXPRESSION 9
#define GROUPSTMT 10
#define INCONTEXT 11

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 56 "l2c.l"



#line 60 "l2c.l"
	if (first_time)
	{
                // Mik 04/2013 - if only parsing the module file, there is nothing to skip 
                if (bModulesOnly)
                  BEGIN NRMLSRC;
                else
		  BEGIN SKIP;
		nested = 0;
		first_time = false;
	}


#line 1309 "l2c_lex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 400 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 762 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "l2c.l"
{ BEGIN NRMLSRC; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 73 "l2c.l"
{ lineno++; DumpOut(l2ctext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "l2c.l"
{ BEGIN EXPRESSION; return tDERIVLENGTH; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "l2c.l"
{ BEGIN EXPRESSION; return tRINGLSYSTEM; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "l2c.l"
{ BEGIN EXPRESSION; return tMAXDEPTH; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "l2c.l"
{ BEGIN MODULE; return tMODULE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "l2c.l"
{ BEGIN CONIGN; return tCONSIDER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "l2c.l"
{ BEGIN CONIGN; return tIGNORE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "l2c.l"
{ BEGIN CONIGN; return tVERIFYSTRING; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "l2c.l"
{ return tINTERPRETATION; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "l2c.l"
{ return tDECOMPOSITION; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "l2c.l"
{ return tPRODUCTION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "l2c.l"
{
	BEGIN PRODUCTION;
	nested = 0;
	return tPRODUCE;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "l2c.l"
{
	BEGIN PRODUCTION;
	nested = 0;
	return tNPRODUCE;
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 96 "l2c.l"
{ return tPROPENSITY; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "l2c.l"
{ BEGIN PRODUCTION; nested = 0; return tAXIOM; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 98 "l2c.l"
{ BEGIN PRODUCTION; nested = 0; return tAXIOM; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 99 "l2c.l"
{ return tSTART; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 100 "l2c.l"
{ return tSTARTEACH; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 101 "l2c.l"
{ return tENDEACH; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "l2c.l"
{ return tEND; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "l2c.l"
{ BEGIN GROUPSTMT; return tGROUP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "l2c.l"
{ BEGIN GROUPSTMT; return tGGROUP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "l2c.l"
{ return tENDGROUP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "l2c.l"
{ BEGIN GROUPSTMT; return tVGROUP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "l2c.l"
{ BEGIN GROUPSTMT; return tVGROUP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "l2c.l"
{ return tENDVGROUP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "l2c.l"
{ return tENDVGROUP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "l2c.l"
{ BEGIN INCONTEXT; nested = 0; return tINRIGHTCONTEXT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "l2c.l"
{ BEGIN INCONTEXT; nested = 0; return tINLEFTCONTEXT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "l2c.l"
{ BEGIN INCONTEXT; nested = 0; return tINNEWRIGHTCONTEXT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "l2c.l"
{ BEGIN INCONTEXT; nested = 0; return tINNEWLEFTCONTEXT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "l2c.l"
{
	if (moduleTable.IsModuleIdent(l2ctext))
	{
	  if (verbose)
	    printf("module recognized: %s\n", l2ctext);
	  strncpy(l2clval.Ident, l2ctext, __lc_eMaxIdentifierLength);
	  l2clval.Ident[__lc_eMaxIdentifierLength] = 0;
	  BEGIN PRODPROTO;
	  return tMODULEIDENT;
	}
	else
	  DumpOut(l2ctext);
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 128 "l2c.l"
{
	if (moduleTable.IsModuleIdent(l2ctext))
	{
		if (verbose)
		  printf("module recognized: %s\n", l2ctext);
		strncpy(l2clval.Ident, l2ctext, __lc_eMaxIdentifierLength);
		l2clval.Ident[__lc_eMaxIdentifierLength] = 0;
		return tMODULEIDENT;
	}
	else
		return tERROR;
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "l2c.l"
{ BEGIN NRMLSRC; return tSEMICOLON; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 143 "l2c.l"
{ return tLPAREN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 144 "l2c.l"
{ return tRPAREN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 145 "l2c.l"
{ return tCOMMA; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 146 "l2c.l"
{ return tEQUALS; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 147 "l2c.l"
{ l2clval.Integer = atoi(l2ctext); return tINTEGER; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 148 "l2c.l"
{ BEGIN NRMLSRC; return tSEMICOLON; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 149 "l2c.l"
{
	strncpy(l2clval.Ident, l2ctext, __lc_eMaxIdentifierLength);
	l2clval.Ident[__lc_eMaxIdentifierLength] = 0;
	return tIDENT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 154 "l2c.l"
{ return tLPAREN; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 155 "l2c.l"
{ return tRPAREN; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 156 "l2c.l"
{ return tCOMMA; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 157 "l2c.l"
{ BEGIN NRMLSRC; return tENDPRODPROTO; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 158 "l2c.l"
{ return tLESSTHAN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 159 "l2c.l"
{ return tGREATERTHAN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 160 "l2c.l"
{ return tLEFTSHIFT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 161 "l2c.l"
{ return tRIGHTSHIFT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 162 "l2c.l"
{
	strncpy(l2clval.Ident, l2ctext, __lc_eMaxIdentifierLength);
	l2clval.Ident[__lc_eMaxIdentifierLength] = 0;
	if (moduleTable.IsModuleIdent(l2ctext))
	{
		if (verbose)
		  printf("module recognized: %s\n", l2ctext);
		return tMODULEIDENT;
	}
	else
		return tIDENT;
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 175 "l2c.l"
{ nested++; if (1==nested) return tLPAREN; else DumpOut(l2ctext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 176 "l2c.l"
{ nested--; if (0==nested) return tRPAREN; else DumpOut(l2ctext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 177 "l2c.l"
{ if (1==nested) return tCOMMA; else DumpOut(l2ctext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 178 "l2c.l"
{
	if (moduleTable.IsModuleIdent(l2ctext))
	{
	  if (verbose)
	    printf("module recognized: %s\n", l2ctext);
	  strncpy(l2clval.Ident, l2ctext, __lc_eMaxIdentifierLength);
	  l2clval.Ident[__lc_eMaxIdentifierLength] = 0;
	  return tMODULEIDENT;
	}
	else
	{
	  if (0==nested)
	    printf("module expected. %s found at %d in %s\n", l2ctext, lineno, FileName);
	  DumpOut(l2ctext);
	}
	}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 194 "l2c.l"
{ BEGIN NRMLSRC; return tSEMICOLON; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 196 "l2c.l"
{ BEGIN NRMLSRC; return tCOLON; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 198 "l2c.l"
{ BEGIN NRMLSRC; DumpOut(l2ctext); return tSEMICOLON; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 200 "l2c.l"
{ 
		++nested; 
		return tLPAREN;
	}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 205 "l2c.l"
{
		--nested;
		if (0==nested)
		{
			BEGIN NRMLSRC;
		}
		return tRPAREN;
	}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 214 "l2c.l"
{
		strncpy(l2clval.Ident, l2ctext, __lc_eMaxIdentifierLength);
		if (moduleTable.IsModuleIdent(l2ctext))
		{
			return tMODULEIDENT;
		}
		else
		{
			return tIDENT;
		}
	}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 226 "l2c.l"
{ return tCOMMA; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 228 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 229 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 230 "l2c.l"
{ BEGIN BeforeString; DumpOut(l2ctext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 232 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 233 "l2c.l"
{ BEGIN BeforeString; DumpOut(l2ctext); }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 235 "l2c.l"
{
	SetCurLine(l2ctext+6);
	DumpOut(l2ctext);
	lineno++;
	}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 240 "l2c.l"
{
	SetCurLine(l2ctext+2);
	DumpOut(l2ctext);
	lineno++;
	}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 246 "l2c.l"
{ BeforeString = YY_START; BEGIN STRING; DumpOut(l2ctext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 247 "l2c.l"
{ BeforeString = YY_START; BEGIN CHARACTER; DumpOut(l2ctext); }
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 249 "l2c.l"
{ lineno++; DumpOut(l2ctext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 251 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 253 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 254 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 257 "l2c.l"
{ DumpOut(l2ctext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 259 "l2c.l"
ECHO;
	YY_BREAK
#line 1849 "l2c_lex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SKIP):
case YY_STATE_EOF(NRMLSRC):
case YY_STATE_EOF(MODULE):
case YY_STATE_EOF(PRODPROTO):
case YY_STATE_EOF(PRODUCTION):
case YY_STATE_EOF(CONIGN):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHARACTER):
case YY_STATE_EOF(EXPRESSION):
case YY_STATE_EOF(GROUPSTMT):
case YY_STATE_EOF(INCONTEXT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 400 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 400 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 399);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 259 "l2c.l"


/*
*/

